source "http://rubygems.org"
source "http://gems.rubyforge.org"
source "http://gemcutter.org"

#gem "jdbc-mysql", "5.1.13"
gem "logger" 
gem "github_api", "0.8.10"
gem "jruby-openssl", "0.7.7"
gem "json", "1.7.4"
gem "xml-simple", "1.1.2"
gem "certified", "0.1.1"
